using System.Collections;
using System.Collections.Generic;

namespace SonglistGeneratorTests
{
    class CaretsWrapperTestData : IEnumerable<object[]>
    {
        public IEnumerator<object[]> GetEnumerator()
        {
            yield return new object[] { "NO CHANGES", changesNotNeeded, changesNotNeeded };
            yield return new object[] { "ONE CHAR - NO BRACES", oneCharNoBracesInput, oneCharNoBracesExpected };
            yield return new object[] { "ONE CHAR - WITH BRACES", oneCharWithBracesInput, oneCharWithBracesExpected };
            yield return new object[] { "MANY CHARS - WITH BRACES", manyCharsWithBracesInput, manyCharsWithBracesExpected };
            yield return new object[] { "MIXED CASE", mixedCaseInput, mixedCaseExpected };
            yield return new object[] { "SONG TEXT CASE", songTextCaseInput, songTextCaseExpected };
        }

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

        private string changesNotNeeded = @"\\tytul{Ech muzyka}{sł. Konstanty Ildefons Gałczyński, muz. Adam Drąg}{Adam Drąg}\n\\begin{text}\n    O, dajcie mi te małe skrzypce,\\\\\n    Może na skrzypcach wygram,\\\\\n    Wiatr i pochyłą ulicę,\\\\\n    I noc, co taka niezwykła.\n\n    \\vin Ech, muzyka, muzyka, muzyka,\\\\\n    \\vin Spod smyka zielony kurz,\\\\\n    \\vin Lecą gwiazdy zielone spod smyka,\\\\\n    \\vin Damy karo, bukiety róż.\n\n    Uwzględnijcie mizerne granie,\\\\\n    A nie bijcie, gdy wezmę źle,\\\\\n    Jaki ton na strunie baraniej,\\\\\n    Na g, d, a, czy e.\n\n    \\vin Ech, muzyka...\n\n    Prowadzi muzyka za smykiem,\\\\\n    Drzewa, w niemej podzięce\\\\\n    Oczami za smykiem suną,\\\\\n    Zgrabiałe, duże ręce.\n\n    \\vin Ech, muzyka...\n\n    Na moście stoją. Przez liście,\\\\\n    Światło na smyk się sypie,\\\\\n    Słuchajcie, to dziecko nuci,\\\\\n    W czarodziejskim pudełku skrzypiec.\n    \n    \\vin Ech, muzyka...\n\\end{text}\n\\begin{chord}\n    G D\\\\\n    C G\\\\\n    C G\\\\\n    D G D\n\n    G A D\\\\\n    G A D Fis\\\\\n    h A D A\\\\\n    G A D\n\\end{chord}";

        // 1) A^7 -> $\mathrm{A^7}$
        private string oneCharNoBracesInput = @"\\tytul{Chyba już czas}{sł. muz. Adam Drąg}{Adam Drąg}\n\\begin{text}\n    Zawinięte w kłębek drogi\\\\\n    Liczą na twój czas,\\\\\n    Zamienione w wielkie słońce,\\\\\n    Dzień powoli gasł.\n\n    \\vin Chyba już czas wracać do domu,\\\\\n    \\vin W słońcu się chyli wierzbiny liść,\\\\\n    \\vin Chyba już czas wracać do domu,\\\\\n    \\vin W ciszy powrotu tak iść mi, iść.\n\n    O zielonej, mokrej ziemi,\\\\\n    Głośniej śpiewa wiatr,\\\\\n    By najkrótszą drogę wybrać,\\\\\n    Wróży z liści kart.\n\n    \\vin Chyba już czas...\n\n    Światło dnia już pobłądziło,\\\\\n    W drzewach i na ścieżce,\\\\\n    Nie okryty zmrokiem został,\\\\\n    Tylko wyraz „jeszcze”.\n\n    \\vin Chyba już czas...\n\\end{text}\n\\begin{chord}\n    C\\\\\n    C^7 G\\\\\n    C F\\\\\n    G^7 C G\n\n    C G a G\\\\\n    C G a G\\\\\n    C G a G\\\\\n    C G a G\n\\end{chord}";
        private string oneCharNoBracesExpected = @"\\tytul{Chyba już czas}{sł. muz. Adam Drąg}{Adam Drąg}\n\\begin{text}\n    Zawinięte w kłębek drogi\\\\\n    Liczą na twój czas,\\\\\n    Zamienione w wielkie słońce,\\\\\n    Dzień powoli gasł.\n\n    \\vin Chyba już czas wracać do domu,\\\\\n    \\vin W słońcu się chyli wierzbiny liść,\\\\\n    \\vin Chyba już czas wracać do domu,\\\\\n    \\vin W ciszy powrotu tak iść mi, iść.\n\n    O zielonej, mokrej ziemi,\\\\\n    Głośniej śpiewa wiatr,\\\\\n    By najkrótszą drogę wybrać,\\\\\n    Wróży z liści kart.\n\n    \\vin Chyba już czas...\n\n    Światło dnia już pobłądziło,\\\\\n    W drzewach i na ścieżce,\\\\\n    Nie okryty zmrokiem został,\\\\\n    Tylko wyraz „jeszcze”.\n\n    \\vin Chyba już czas...\n\\end{text}\n\\begin{chord}\n    C\\\\\n    $\mathrm{C^7}$ G\\\\\n    C F\\\\\n    $\mathrm{G^7}$ C G\n\n    C G a G\\\\\n    C G a G\\\\\n    C G a G\\\\\n    C G a G\n\\end{chord}";

        // 2) h^{7} -> $\mathrm{h^{7}}$
        private string oneCharWithBracesInput = @"%%\n%% Author: bartek.rydz\n%% 14.02.2019\n%%\n% Preamble\n\\tytul{Ja wysiadam}{sł. M. Czapińska, muz. M. Pospieszalski}{Anna Maria Jopek}\n\\begin{text}\n    Niech ktoś zatrzyma wreszcie świat\\\\\n    Ja wysiadam\\\\\n    Na pierwszej stacji, teraz, tu\\\\\n    Niech ktoś zatrzyma wreszcie świat\\\\\n    Bo wysiadam\\\\\n    Przez życie nie chcę gnać bez tchu\n\n    Jak w kołowrotku bezwolnie się kręcę\\\\\n    Gubiąc wątek i dni\\\\\n    A jakiś bies wciąż powtarza mi: prędzej\n\n    A życie przecież po to jest,\\\\\n    żeby pożyć\\\\\n    By spytać siebie: mieć czy być?\\\\\n    Bo życie przecież po to jest,\\\\\n    żeby pożyć\\\\\n    Nim w kołowrotku pęknie nić\n\n    Jak w kołowrotku bezwolnie się kręcę\\\\\n    Gubiąc wątek i dni\\\\\n    A jakiś bies wciąż powtarza mi: prędzej\n\n    Niech ktoś zatrzyma wreszcie świat\\\\\n    Ja wysiadam\\\\\n    Na pierwszej stacji, teraz, tu\\\\\n    Już nie chcę z nikim ścigać się\\\\\n    Z sił opadam\\\\\n    Przez życie nie chcę gnać bez tchu\n\n    Będę tracić czas\\\\\n    Szukać dobrych gwiazd\\\\\n    Gapić się na dziury w niebie\\\\\n    Jak najdłużej kochać Ciebie\\\\\n    Na to nie szkoda mi\\\\\n    Zmierzchów, poranków i nocy\n\n    Jak w kołowrotku...\n\\end{text}\n\\begin{chord}\n    a d E^{7}\\\\\n    E\\\\\n    a d E (FEa)\\\\\n    a d E^{7}\\\\\n    E\\\\\n    a d E\n\n    A A^{7}\\\\\n    d\\\\\n    d\n\n    a d E^{7}\\\\\n    E\\\\\n    a d E (FEa)\\\\\n    a d E^{7}\\\\\n    E\\\\\n    a d E\n\n    A A^{7}\\\\\n    d\\\\\n    d\n\n    a d E^{7}\\\\\n    E\\\\\n    a d E (FEa)\\\\\n    a d E^{7}\\\\\n    E\\\\\n    a d E\n\n    d a\\\\\n    d a\\\\\n    d\\\\\n    a\\\\\n    F\\\\\n    a (FE)\n\\end{chord}";
        private string oneCharWithBracesExpected = @"%%\n%% Author: bartek.rydz\n%% 14.02.2019\n%%\n% Preamble\n\\tytul{Ja wysiadam}{sł. M. Czapińska, muz. M. Pospieszalski}{Anna Maria Jopek}\n\\begin{text}\n    Niech ktoś zatrzyma wreszcie świat\\\\\n    Ja wysiadam\\\\\n    Na pierwszej stacji, teraz, tu\\\\\n    Niech ktoś zatrzyma wreszcie świat\\\\\n    Bo wysiadam\\\\\n    Przez życie nie chcę gnać bez tchu\n\n    Jak w kołowrotku bezwolnie się kręcę\\\\\n    Gubiąc wątek i dni\\\\\n    A jakiś bies wciąż powtarza mi: prędzej\n\n    A życie przecież po to jest,\\\\\n    żeby pożyć\\\\\n    By spytać siebie: mieć czy być?\\\\\n    Bo życie przecież po to jest,\\\\\n    żeby pożyć\\\\\n    Nim w kołowrotku pęknie nić\n\n    Jak w kołowrotku bezwolnie się kręcę\\\\\n    Gubiąc wątek i dni\\\\\n    A jakiś bies wciąż powtarza mi: prędzej\n\n    Niech ktoś zatrzyma wreszcie świat\\\\\n    Ja wysiadam\\\\\n    Na pierwszej stacji, teraz, tu\\\\\n    Już nie chcę z nikim ścigać się\\\\\n    Z sił opadam\\\\\n    Przez życie nie chcę gnać bez tchu\n\n    Będę tracić czas\\\\\n    Szukać dobrych gwiazd\\\\\n    Gapić się na dziury w niebie\\\\\n    Jak najdłużej kochać Ciebie\\\\\n    Na to nie szkoda mi\\\\\n    Zmierzchów, poranków i nocy\n\n    Jak w kołowrotku...\n\\end{text}\n\\begin{chord}\n    a d $\mathrm{E^{7}}$\\\\\n    E\\\\\n    a d E (FEa)\\\\\n    a d $\mathrm{E^{7}}$\\\\\n    E\\\\\n    a d E\n\n    A $\mathrm{A^{7}}$\\\\\n    d\\\\\n    d\n\n    a d $\mathrm{E^{7}}$\\\\\n    E\\\\\n    a d E (FEa)\\\\\n    a d $\mathrm{E^{7}}$\\\\\n    E\\\\\n    a d E\n\n    A $\mathrm{A^{7}}$\\\\\n    d\\\\\n    d\n\n    a d $\mathrm{E^{7}}$\\\\\n    E\\\\\n    a d E (FEa)\\\\\n    a d $\mathrm{E^{7}}$\\\\\n    E\\\\\n    a d E\n\n    d a\\\\\n    d a\\\\\n    d\\\\\n    a\\\\\n    F\\\\\n    a (FE)\n\\end{chord}";

        // 3) F^{7+} -> $\mathrm{F^{7+}}$
        private string manyCharsWithBracesInput = @"%%\n%% Author: bartek.rydz\n%% 10.02.2019\n%%\n% Preamble\n\\tytul{Chyba już można iść spać}{}{Andrzej Poniedzielski}\n\\begin{text}\n    \\vin Chyba już można iść spać\\\\\n    \\vin Dziś pewnie nic się nie zdarzy\\\\\n    \\vin Chyba już można się położyć\\\\\n    \\vin Marzeń na jutro trzeba namarzyć\n\n    Tamtą kartkę z wczorajszej nocy\\\\\n    Trzeba zmiąć i położyć w koszu\\\\\n    I od nowa, na nowej kartce\\\\\n    Pisać nowy, niemiłosny list do losu\n\n    Albo donos pisać na życie\\\\\n    Bo należy mu się swoją drogą\\\\\n    I podpisać zgryźliwie 'życzliwy'\\\\\n    Tylko gdzie to wysłać, do kogo\n\n    Takie łóżko, a taka dobra rzecz\\\\\n    To był świetny pomysł z tym łóżkiem\\\\\n    Jak ktoś chce sobie życie poprawić\\\\\n    To wystarczy poprawić poduszkę\n\\end{text}\n\\begin{chord}\n    C F^{7+} e\\\\\n    C F^{7+} e\\\\\n    C F^{7+} e\\\\\n    C Ce C\n\n    g f\\\\\n    g d\\\\\n    g f\\\\\n    g f C\n\n    g f\\\\\n    g d\\\\\n    g f\\\\\n    g f C\n\n    g f\\\\\n    g d\\\\\n    g f\\\\\n    g f C\n\\end{chord}";
        private string manyCharsWithBracesExpected = @"%%\n%% Author: bartek.rydz\n%% 10.02.2019\n%%\n% Preamble\n\\tytul{Chyba już można iść spać}{}{Andrzej Poniedzielski}\n\\begin{text}\n    \\vin Chyba już można iść spać\\\\\n    \\vin Dziś pewnie nic się nie zdarzy\\\\\n    \\vin Chyba już można się położyć\\\\\n    \\vin Marzeń na jutro trzeba namarzyć\n\n    Tamtą kartkę z wczorajszej nocy\\\\\n    Trzeba zmiąć i położyć w koszu\\\\\n    I od nowa, na nowej kartce\\\\\n    Pisać nowy, niemiłosny list do losu\n\n    Albo donos pisać na życie\\\\\n    Bo należy mu się swoją drogą\\\\\n    I podpisać zgryźliwie 'życzliwy'\\\\\n    Tylko gdzie to wysłać, do kogo\n\n    Takie łóżko, a taka dobra rzecz\\\\\n    To był świetny pomysł z tym łóżkiem\\\\\n    Jak ktoś chce sobie życie poprawić\\\\\n    To wystarczy poprawić poduszkę\n\\end{text}\n\\begin{chord}\n    C $\mathrm{F^{7+}}$ e\\\\\n    C $\mathrm{F^{7+}}$ e\\\\\n    C $\mathrm{F^{7+}}$ e\\\\\n    C Ce C\n\n    g f\\\\\n    g d\\\\\n    g f\\\\\n    g f C\n\n    g f\\\\\n    g d\\\\\n    g f\\\\\n    g f C\n\n    g f\\\\\n    g d\\\\\n    g f\\\\\n    g f C\n\\end{chord}";

        // 4) First and third case in one song
        private string mixedCaseInput = @"%%\n%% Author: bartek.rydz\n%% 24.05.2018\n%%\n\n% Preamble\n\\tytul{Beskid}{sł. muz. Andrzej Wierzbicki}{SETA}\n\\begin{text}\n    A w Beskidzie rozzłocony buk,\\\\\n    A w Beskidzie rozzłocony buk.\\\\\n    Będę chodził Bukowiną\\\\\n\tz dłutem w ręku by w dziewczęcych twarzach \\\\\n    Uśmiech rzeźbić, niech nie płaczą już\\\\\n    Niech się cieszą po kapliczkach moich dróg.\n\n    \\vin Beskidzie, malowany cerkiewny dach,\\\\\n    \\vin Beskidzie, zapach miodu w bukowych pniach.\\\\\n    \\vin Tutaj wracam, gdy ruda jesień\\\\\n    \\vin Na przełęcze swój tobół niesie,\\\\\n    \\vin Słucham bicia dzwonów w przedwieczorny czas.\n\n    \\vin Beskidzie, malowany wiatrami dom,\\\\\n    \\vin Beskidzie, tutaj słowa inaczej brzmią,\\\\\n    \\vin Kiedy krzyczą w jesienną ciszę,\\\\\n    \\vin Kiedy wiatrem szeleszczą liście,\\\\\n    \\vin Kiedy wolność się tuli w ciepło moich rąk,\\\\\n    \\vin Gdy jak źrebak się tuli do moich rąk.\n\n    A w Beskidzie zamyślony czas,\\\\\n    A w Beskidzie zamyślony czas.\\\\\n    Będę chodził z nim poddaszem gór,\\\\\n    By zerwanych marzeń struny\\\\\n    Przywiązywać w niepokój i dłonie drzew,\\\\\n    Niech mi grają na rozstajach moich dróg.\n\n    \\vin Beskidzie...\n\\end{text}\n\\begin{chord}\n    G CDG CD\\\\\n\tG C e a D^7\\\\\n\tC D^7\\\\\n\tG C\\\\\n\tG C C^{7+} a D^7\\\\\n\tC D G C D\n\t\n\tG C D G\\\\\n\tG C H^7 e\\\\\n\tC D^7\\\\\n\tG C\\\\\n\tG C C^7 a D^7\\\\\n\t(C D G)\n\t\n\\end{chord}";
        private string mixedCaseExpected = @"%%\n%% Author: bartek.rydz\n%% 24.05.2018\n%%\n\n% Preamble\n\\tytul{Beskid}{sł. muz. Andrzej Wierzbicki}{SETA}\n\\begin{text}\n    A w Beskidzie rozzłocony buk,\\\\\n    A w Beskidzie rozzłocony buk.\\\\\n    Będę chodził Bukowiną\\\\\n\tz dłutem w ręku by w dziewczęcych twarzach \\\\\n    Uśmiech rzeźbić, niech nie płaczą już\\\\\n    Niech się cieszą po kapliczkach moich dróg.\n\n    \\vin Beskidzie, malowany cerkiewny dach,\\\\\n    \\vin Beskidzie, zapach miodu w bukowych pniach.\\\\\n    \\vin Tutaj wracam, gdy ruda jesień\\\\\n    \\vin Na przełęcze swój tobół niesie,\\\\\n    \\vin Słucham bicia dzwonów w przedwieczorny czas.\n\n    \\vin Beskidzie, malowany wiatrami dom,\\\\\n    \\vin Beskidzie, tutaj słowa inaczej brzmią,\\\\\n    \\vin Kiedy krzyczą w jesienną ciszę,\\\\\n    \\vin Kiedy wiatrem szeleszczą liście,\\\\\n    \\vin Kiedy wolność się tuli w ciepło moich rąk,\\\\\n    \\vin Gdy jak źrebak się tuli do moich rąk.\n\n    A w Beskidzie zamyślony czas,\\\\\n    A w Beskidzie zamyślony czas.\\\\\n    Będę chodził z nim poddaszem gór,\\\\\n    By zerwanych marzeń struny\\\\\n    Przywiązywać w niepokój i dłonie drzew,\\\\\n    Niech mi grają na rozstajach moich dróg.\n\n    \\vin Beskidzie...\n\\end{text}\n\\begin{chord}\n    G CDG CD\\\\\n\tG C e a $\mathrm{D^7}$\\\\\n\tC $\mathrm{D^7}$\\\\\n\tG C\\\\\n\tG C $\mathrm{C^{7+}}$ a $\mathrm{D^7}$\\\\\n\tC D G C D\n\t\n\tG C D G\\\\\n\tG C $\mathrm{H^7}$ e\\\\\n\tC $\mathrm{D^7}$\\\\\n\tG C\\\\\n\tG C $\mathrm{C^7}$ a $\mathrm{D^7}$\\\\\n\t(C D G)\n\t\n\\end{chord}";

        // 5) Standard case, but including song text
        private string songTextCaseInput = @"\\tytul{Po sezonie}{sł. Wiesław Buchcic, muz. Ryszard Pomorski}{Wołosatki}\r\n\\begin{text}\r\n    \\textit{C D^7 G}\\\\\r\n    Złotym kobiercem wymoszczone góry,\\\\\r\n    Jesień w doliny przyszła dziś nad ranem.\\\\\r\n    Buki czerwienią zabarwiły chmury,\\\\\r\n    Z latem się złotym właśnie pożegnałem\r\n\r\n    \\vin We wtorek w schronisku po sezonie,\\\\\r\n    \\vin W doliny wczoraj zszedł ostatni gość.\\\\\r\n    \\vin Za oknem plucha, kubek parzy dłonie,\\\\\r\n    \\vin I tej herbaty, i tych gór mam dość.\r\n\r\n    Szaruga niebo powoli zasnuwa,\\\\\r\n    Wiatr już gałęzie pootrząsał z liści.\\\\\r\n    Pod wiatr, pod górę znowu sam zasuwam,\\\\\r\n    może w schronisku spotkam kogoś z bliskich.\r\n\r\n    \\vin We wtorek...\r\n\r\n    Ludzie tak wiele spraw muszą załatwić,\\\\\r\n    A czas sobie płynie wolno panta rhei.\\\\\r\n    Do siebie tylko już nie umiem trafić,\\\\\r\n    Kochać to więcej z siebie dać, czy mniej.\r\n\r\n    \\vin We wtorek...\r\n\\end{text}\r\n\\begin{chord}\r\n    \\textit{Capo II}\\\\\r\n    G C G\\\\\r\n    h C a D^7\\\\\r\n    G C H^7 e\\\\\r\n    C D G D\r\n\r\n    G C D G\\\\\r\n    e A a^7 D^7\\\\\r\n    G C H^7 e\\\\\r\n    C D^7 G D\r\n\\end{chord}";
        private string songTextCaseExpected = @"\\tytul{Po sezonie}{sł. Wiesław Buchcic, muz. Ryszard Pomorski}{Wołosatki}\r\n\\begin{text}\r\n    \\textit{C $\mathrm{D^7}$ G}\\\\\r\n    Złotym kobiercem wymoszczone góry,\\\\\r\n    Jesień w doliny przyszła dziś nad ranem.\\\\\r\n    Buki czerwienią zabarwiły chmury,\\\\\r\n    Z latem się złotym właśnie pożegnałem\r\n\r\n    \\vin We wtorek w schronisku po sezonie,\\\\\r\n    \\vin W doliny wczoraj zszedł ostatni gość.\\\\\r\n    \\vin Za oknem plucha, kubek parzy dłonie,\\\\\r\n    \\vin I tej herbaty, i tych gór mam dość.\r\n\r\n    Szaruga niebo powoli zasnuwa,\\\\\r\n    Wiatr już gałęzie pootrząsał z liści.\\\\\r\n    Pod wiatr, pod górę znowu sam zasuwam,\\\\\r\n    może w schronisku spotkam kogoś z bliskich.\r\n\r\n    \\vin We wtorek...\r\n\r\n    Ludzie tak wiele spraw muszą załatwić,\\\\\r\n    A czas sobie płynie wolno panta rhei.\\\\\r\n    Do siebie tylko już nie umiem trafić,\\\\\r\n    Kochać to więcej z siebie dać, czy mniej.\r\n\r\n    \\vin We wtorek...\r\n\\end{text}\r\n\\begin{chord}\r\n    \\textit{Capo II}\\\\\r\n    G C G\\\\\r\n    h C a $\mathrm{D^7}$\\\\\r\n    G C $\mathrm{H^7}$ e\\\\\r\n    C D G D\r\n\r\n    G C D G\\\\\r\n    e A $\mathrm{a^7}$ $\mathrm{D^7}$\\\\\r\n    G C $\mathrm{H^7}$ e\\\\\r\n    C $\mathrm{D^7}$ G D\r\n\\end{chord}";
    }
}
