name: Build Songbook

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Chechout repository
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
          
    - name: Install tests dependencies
      run: dotnet restore $GITHUB_WORKSPACE/SonglistGeneratorTests/SonglistGeneratorTests.csproj
    
    - name: Build tests
      run: dotnet build $GITHUB_WORKSPACE/SonglistGeneratorTests/SonglistGeneratorTests.csproj --configuration Release --no-restore
      
    - name: Run tests
      run: dotnet test $GITHUB_WORKSPACE/SonglistGeneratorTests/SonglistGeneratorTests.csproj --no-restore --verbosity normal
      
    - name: Install SonglistGenerator dependencies
      run: dotnet restore $GITHUB_WORKSPACE/SonglistGenerator/SonglistGenerator.csproj
    
    - name: Build SonglistGenerator
      run: dotnet build $GITHUB_WORKSPACE/SonglistGenerator/SonglistGenerator.csproj --configuration Release --no-restore
      
    - name: Run SonglistGenerator
      run: dotnet $GITHUB_WORKSPACE/SonglistGenerator/bin/Release/net5.0/SonglistGenerator.dll $GITHUB_WORKSPACE/main "$GITHUB_WORKSPACE/Songbook v2.0 r${{github.run_number}}" 1
    
    - name: Upload SonglistGenerator.dll
      uses: actions/upload-artifact@v2
      with:
        name: SonglistGenerator DLL r${{github.run_number}}
        path: SonglistGenerator/bin/Release/net5.0/SonglistGenerator.dll
        
    - name: Upload zip file with songbook source, containing new main and master files
      uses: actions/upload-artifact@v2
      with:
        name: Songbook v2.0 r${{github.run_number}}_source
        path: Songbook v2.0 r${{github.run_number}}
      
    - name: Compile songbook
      uses: xu-cheng/latex-action@v2
      with:
        root_file: "Spiewnik_chwyty.tex"
        working_directory: "Songbook v2.0 r${{github.run_number}}"
        
    - name: Upload generated PDF
      uses: actions/upload-artifact@v2
      with:
        name: Songbook v2.0 r${{github.run_number}}_pdf
        path: Songbook v2.0 r${{github.run_number}}/Spiewnik_chwyty.pdf
        
    - name: Upload generated PDF (output log)
      uses: actions/upload-artifact@v2
      with:
        name: Songbook v2.0 r${{github.run_number}}_pdf
        path: Songbook v2.0 r${{github.run_number}}/Spiewnik_chwyty.log
